CREATE TABLE "rol" (
  "id_rol" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "area" (
  "id_area" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL,
  "descripcion" text,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "usuario" (
  "id_usuario" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "correo" varchar(150) UNIQUE NOT NULL,
  "contrasena_hash" varchar(255) NOT NULL,
  "id_rol" integer NOT NULL,
  "id_area" integer NOT NULL,
  "cargo" varchar(100),
  "fecha_ingreso" date,
  "fecha_registro" date NOT NULL DEFAULT (CURRENT_DATE),
  "estado" varchar(20) NOT NULL DEFAULT 'activo'
);

CREATE TABLE "jornada_laboral" (
  "id_jornada" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer NOT NULL,
  "hora_inicio" time NOT NULL,
  "hora_fin" time NOT NULL,
  "hora_almuerzo_inicio" time,
  "hora_almuerzo_fin" time,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "rutina" (
  "id_rutina" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(150) NOT NULL,
  "tipo" varchar(30) NOT NULL,
  "descripcion" text,
  "duracion_estimada" integer NOT NULL,
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "ejercicio" (
  "id_ejercicio" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_rutina" integer NOT NULL,
  "nombre" varchar(150) NOT NULL,
  "descripcion" text,
  "instrucciones" text NOT NULL,
  "duracion" integer NOT NULL,
  "imagen_url" varchar(500),
  "orden" integer NOT NULL DEFAULT 1
);

CREATE TABLE "pausa_programada" (
  "id_pausa" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer NOT NULL,
  "id_rutina" integer NOT NULL,
  "hora_programada" time NOT NULL,
  "duracion_minutos" integer NOT NULL DEFAULT 5,
  "frecuencia" varchar(20) NOT NULL DEFAULT 'diaria',
  "estado" varchar(20) NOT NULL DEFAULT 'pendiente',
  "activa" boolean NOT NULL DEFAULT true
);

CREATE TABLE "registro_pausa" (
  "id_registro" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pausa" integer NOT NULL,
  "fecha" date NOT NULL DEFAULT (CURRENT_DATE),
  "hora_inicio" timestamp NOT NULL,
  "hora_fin" timestamp,
  "estado_cumplimiento" varchar(20) NOT NULL DEFAULT 'pendiente',
  "modo_no_molestar" boolean NOT NULL DEFAULT false
);

CREATE TABLE "notificacion" (
  "id_notificacion" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_pausa" integer NOT NULL,
  "titulo" varchar(150) NOT NULL,
  "mensaje" varchar(500) NOT NULL,
  "hora_envio" timestamp NOT NULL,
  "canal" varchar(20) NOT NULL DEFAULT 'push',
  "estado_envio" varchar(20) NOT NULL DEFAULT 'pendiente',
  "leida" boolean NOT NULL DEFAULT false
);

CREATE TABLE "alerta" (
  "id_alerta" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_usuario" integer NOT NULL,
  "tipo" varchar(30) NOT NULL,
  "descripcion" text NOT NULL,
  "fecha_generacion" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "resuelta" boolean NOT NULL DEFAULT false
);

CREATE INDEX ON "usuario" ("id_rol");

CREATE INDEX ON "usuario" ("id_area");

CREATE INDEX ON "jornada_laboral" ("id_usuario");

CREATE INDEX ON "ejercicio" ("id_rutina");

CREATE UNIQUE INDEX ON "ejercicio" ("id_rutina", "orden");

CREATE INDEX ON "pausa_programada" ("id_usuario");

CREATE INDEX ON "pausa_programada" ("id_rutina");

CREATE INDEX ON "registro_pausa" ("id_pausa");

CREATE INDEX ON "registro_pausa" ("id_pausa", "fecha");

CREATE INDEX ON "notificacion" ("id_pausa");

CREATE INDEX ON "alerta" ("id_usuario");

COMMENT ON COLUMN "rol"."nombre" IS 'administrador | trabajador';

COMMENT ON COLUMN "usuario"."contrasena_hash" IS 'bcrypt costo 12';

COMMENT ON COLUMN "usuario"."estado" IS 'activo | inactivo | suspendido';

COMMENT ON COLUMN "rutina"."tipo" IS 'estiramiento | movilidad | visual | respiracion';

COMMENT ON COLUMN "rutina"."duracion_estimada" IS 'minutos, 1 a 30';

COMMENT ON COLUMN "ejercicio"."duracion" IS 'segundos';

COMMENT ON COLUMN "pausa_programada"."duracion_minutos" IS 'entre 5 y 10, criterio de RF-02';

COMMENT ON COLUMN "pausa_programada"."frecuencia" IS 'diaria | semanal | unica';

COMMENT ON TABLE "registro_pausa" IS 'Sin id_usuario ni duracion_real: se obtienen por JOIN y por calculo (correccion de 3FN)';

COMMENT ON COLUMN "registro_pausa"."estado_cumplimiento" IS 'pendiente | cumplida | parcial | omitida';

COMMENT ON COLUMN "notificacion"."canal" IS 'push | email | interna';

COMMENT ON COLUMN "alerta"."tipo" IS 'incumplimiento | inactividad | sistema';

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_rol") REFERENCES "rol" ("id_rol") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "usuario" ADD FOREIGN KEY ("id_area") REFERENCES "area" ("id_area") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "jornada_laboral" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ejercicio" ADD FOREIGN KEY ("id_rutina") REFERENCES "rutina" ("id_rutina") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pausa_programada" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "pausa_programada" ADD FOREIGN KEY ("id_rutina") REFERENCES "rutina" ("id_rutina") ON DELETE RESTRICT ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "registro_pausa" ADD FOREIGN KEY ("id_pausa") REFERENCES "pausa_programada" ("id_pausa") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notificacion" ADD FOREIGN KEY ("id_pausa") REFERENCES "pausa_programada" ("id_pausa") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "alerta" ADD FOREIGN KEY ("id_usuario") REFERENCES "usuario" ("id_usuario") ON DELETE CASCADE ON UPDATE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
